// <auto-generated />
namespace JOB_Site.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Apply_For_Job : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Apply_For_Job));
        
        string IMigrationMetadata.Id
        {
            get { return "202008111314334_Apply_For_Job"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
